CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR (30) NOT NULL,
    ESTADO CHAR(2) NOT NULL, 
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE) 
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE) 
);

/*
    ENDEREÇO - OBRIGATÓRIO CADASTRO DE SOMENTE UM

    TELEFONE - NÃO OBRIGATÓRIO CADASTRO DE MAIS DE UM (OPCIONAL)
*/

/*
    CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA DE UMA TABELA QUE
    VAI ATÉ A OUTRA TABELA E FAZ REFERÊNCIA ENTRE REGISTROS
*/

/* EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICARÁ SEMPRE NA CARDINALIDADE N */

INSERT INTO CLIENTE VALUES(NULL, 'JOAO','M','joao@ig.com','78945845899');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS','M','carlos@ig.com','7899845899');
INSERT INTO CLIENTE VALUES(NULL, 'ANA','F','ana@ig.com','78945844899');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA','F',NULL,'1145845899');
INSERT INTO CLIENTE VALUES(NULL, 'JORGE','M','jorge@ig.com','78945454567');
INSERT INTO CLIENTE VALUES(NULL, 'CELIA','F','celia@ig.com','48998587856');

DESC ENDERECO;

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',1);
INSERT INTO ENDERECO VALUES(NULL,'CAPITÃO HERMES','CENTRO','RIO DE JANEIRO','RJ',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRESIDENTE VARGAS','JARDINS','SÃO PAULO','SP',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',9);

/**/

INSERT INTO TELEFONE VALUES(NULL, 'CEL', '1197785451', 5);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '1155557785', 5);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '2565255555', 1);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '1598452555', 2);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '1125665544', 1);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '1698562145', 9);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '2145987414', 8);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '2465256555', 4);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '0155215452', 4);

/* SELECAO, PROJECAO, JUNÇÃO */

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()

/* PROJEÇÃO É TUDO QUE VOCE QUER VER NA TELA */

/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
    A CLAUSULA DE SELEÇÃO É O > WHERE <
 */

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE           /* "ORIGEM" */ 
WHERE SEXO = 'F';   /* SELEÇÃO*/

SELECT NUMERO
FROM TELEFONE
WHERE TIPO = 'CEL';